# A->W one shot
# da_dis_para
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --task aw --output_path snapshot/aw/uda_dis_aw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --output_path snapshot/aw/dca_dis_aw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --sampler cls_balance --output_path snapshot/aw/dca_dis_cb_aw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --sampler scp_d --output_path snapshot/aw/dca_dis_scpd_aw/

# da_adv_para
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --task aw --output_path snapshot/aw/uda_dis_aw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --output_path snapshot/aw/dca_dis_aw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --sampler cls_balance --output_path snapshot/aw/dca_dis_cb_aw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task aw --sampler scp_d --output_path snapshot/aw/dca_dis_scpd_aw/
