# W->A one shot
# da_dis_para
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --task wa --output_path snapshot/wa/uda_dis_wa/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --output_path snapshot/wa/dca_dis_wa/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --sampler cls_balance --output_path snapshot/wa/dca_dis_cb_wa/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --sampler scp_d --output_path snapshot/wa/dca_dis_scpd_wa/

# da_adv_para
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --task wa --output_path snapshot/wa/uda_dis_wa/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --output_path snapshot/wa/dca_dis_wa/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --sampler cls_balance --output_path snapshot/wa/dca_dis_cb_wa/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task wa --sampler scp_d --output_path snapshot/wa/dca_dis_scpd_wa/
