# D->A one shot
# da_dis_para
python train_da_dis_para.py --gpu 2 --source_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --task da --output_path snapshot/da/uda_dis_da/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --output_path snapshot/da/dca_dis_da/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --sampler cls_balance --output_path snapshot/da/dca_dis_cb_da/
python train_da_dis_para.py --gpu 2 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --sampler scp_d --output_path snapshot/da/dca_dis_scpd_da/

# da_adv_para
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --task da --output_path snapshot/da/uda_dis_da/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --output_path snapshot/da/dca_dis_da/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --sampler cls_balance --output_path snapshot/da/dca_dis_cb_da/
python train_da_adv_para.py --gpu 2 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addAmazon.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_20_oneshot.txt --task da --sampler scp_d --output_path snapshot/da/dca_dis_scpd_da/
