# D->W one shot
# da_dis_para
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --task dw --output_path snapshot/dw/uda_dis_dw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --output_path snapshot/dw/dca_dis_dw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --sampler cls_balance --output_path snapshot/dw/dca_dis_cb_dw/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --sampler scp_d --output_path snapshot/dw/dca_dis_scpd_dw/

# da_adv_para
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/webcam_20.txt --task dw --output_path snapshot/dw/uda_dis_dw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --output_path snapshot/dw/dca_dis_dw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --sampler cls_balance --output_path snapshot/dw/dca_dis_cb_dw/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_10_oneshot_addWebcam.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/webcam_20_oneshot.txt --task dw --sampler scp_d --output_path snapshot/dw/dca_dis_scpd_dw/
