# A->D one shot
# da_dis_para
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --task ad --output_path snapshot/ad/uda_dis_ad/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --output_path snapshot/ad/dca_dis_ad/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --sampler cls_balance --output_path snapshot/ad/dca_dis_cb_ad/
python train_da_dis_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --sampler scp_d --output_path snapshot/ad/dca_dis_scpd_ad/

# da_adv_para
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_20/amazon_20.txt --target_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --test_path /home/changhuiying/DCAN-master/data/list/office_20/dslr_20.txt --task ad --output_path snapshot/ad/uda_dis_ad/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --output_path snapshot/ad/dca_dis_ad/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --sampler cls_balance --output_path snapshot/ad/dca_dis_cb_ad/
python train_da_adv_para.py --gpu 1 --source_path /home/changhuiying/DCAN-master/data/list/office_cida/amazon_10_oneshot_addDslr.txt --target_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --test_path /home/changhuiying/DCAN-master/data/list/office_cida/dslr_20_oneshot.txt --task ad --sampler scp_d --output_path snapshot/ad/dca_dis_scpd_ad/
